#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import webbrowser
import Jalapeno.GUI
from Jalapeno.Globalvar import events,Event,engine

def redirect_thread():
	webbrowser.open('http://127.0.0.1:5588/redirect')
	time.sleep(1)
	
def main():
	try:
		engine.Listen(event=events['GUI'])
		engine.Start()
	except:
		exit()
	
if __name__ =='__main__':
	main()
	