#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import webbrowser
import Jalapeno.GUI.G
from Jalapeno.Globalvar import events,Event,engine
from sys import exit
import time



def main():
	
	try:
		engine.Listen(event=events['GUI'])
		engine.Listen(event=events['Browse'])
		engine.Start()
		
	except:
		pass
	
if __name__ =='__main__':
	main()
	
	
