#!/usr/bin/python3
# -*- coding: UTF-8 -*-
import webbrowser
import Jalapeno.GUI
from Jalapeno.Globalvar import events,Event,engine
from sys import exit
import time
def browser_start(website='http://127.0.0.1:5588/redirect'):
	webbrowser.open(website)
events['Browse']=Event('Browse','Thread',browser_start)
engine.Listen(event=events['Browse'])
def main():
	
	try:
		engine.Listen(event=events['GUI'])
		engine.Start()
		
	except:
		pass
	
if __name__ =='__main__':
	main()
	
	
