#网页信息配置（Site Info config）

Name: 老钱
Motto: 你总有一个坚持下去的理由
Github: https://github.com/ChenghaoQ
copyright: ChenghaoQ


Theme: Jala
views:
  # - postwall
  # - copyright
  - article
  # - about
  # - tags
  - index

Pagination: False
